### ISSUE TITLE
broken link from main website to GitHub

### ISSUE THREAD

**Issue by yzorg** [MaterialDesignInXAML/Website#1]
This link is broken:
https://github.com/MaterialDesignInXAML/Website/blob/master/views/partials/home.html#L18

It looks like you might be planning to migrate it to /MaterialDesignInXAML organization, but while it is still in ButchersBoy account the link is missing `Toolkit`:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit

Would you like a PR?

**Comment by ButchersBoy** [comment]
Yes please! I am in the pub ;)

**Comment by ButchersBoy** [comment]
Fixed, thanks for pointing it out.
